name: ci
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'pnpm' }
      - run: pnpm install
      - run: pnpm -r run typecheck
      - run: pnpm -r run build
      - run: pnpm -r run lint || true
      - run: pnpm -r run test || true
      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium
      - name: Install Playwright system deps (Linux only)
        run: sudo npx playwright install-deps
  python:
    if: hashFiles('pyproject.toml') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -e .[dev] || true
      - run: pip install ruff mypy pytest || true
      - run: ruff check .
      - run: mypy .
      - run: pytest -q || true
  go:
    if: hashFiles('go.mod') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - run: go vet ./...
      - run: go build ./...
  rust:
    if: hashFiles('**/Cargo.toml') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo clippy -- -D warnings
